language: cpp

compiler:
  - gcc

# This is the minimal amount of configuration required to install the build
# dependencies using the debian/control information.

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq devscripts equivs lintian
  - mk-build-deps -i -s sudo

# The --preserve-env and --preserve-envar PATH options are to allow
# dpkg-buildpackage to build the package using the compilers specified in the
# current Travis build environment.

script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b

after_success:
  - sudo dpkg -i ../alsa-midi-latency-test*.deb
  - sudo apt-get -f install
  - alsa-midi-latency-test -V
  - lintian -i ../lsa-midi-latency-test*.dsc
